# Generated by Django 2.1.7 on 2019-02-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantsite', '0002_auto_20190222_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantCsv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alsoknownas', models.TextField(blank=True, db_column='AlsoKnownAs', null=True)),
                ('botanicalname', models.TextField(blank=True, db_column='BotanicalName', null=True)),
                ('planttype', models.TextField(blank=True, db_column='PlantType', null=True)),
                ('lightrequirement', models.TextField(blank=True, db_column='LightRequirement', null=True)),
                ('waterdemand', models.TextField(blank=True, db_column='WaterDemand', null=True)),
                ('landscapeuse', models.TextField(blank=True, db_column='LandscapeUse', null=True)),
                ('ornamentalvalue', models.TextField(blank=True, db_column='OrnamentalValue', null=True)),
                ('nativeadapted', models.TextField(blank=True, db_column='NativeAdapted', null=True)),
                ('wildlifevalue', models.TextField(blank=True, db_column='WildlifeValue', null=True)),
                ('season', models.TextField(blank=True, db_column='Season', null=True)),
                ('deciduousevergreen', models.TextField(blank=True, db_column='DeciduousEvergreen', null=True)),
                ('plantform', models.TextField(blank=True, db_column='PlantForm', null=True)),
                ('plantspread', models.TextField(blank=True, db_column='PlantSpread', null=True)),
                ('plantheight', models.TextField(blank=True, db_column='PlantHeight', null=True)),
            ],
            options={
                'db_table': 'plant_csv',
                'managed': False,
            },
        ),
    ]
