# Generated by Django 2.1.5 on 2019-03-27 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantsite', '0003_plantcsv'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantEcoregions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbid', models.IntegerField(blank=True, null=True)),
                ('ecoregion', models.TextField(blank=True, db_column='Ecoregion', null=True)),
                ('paragraph', models.TextField(blank=True, db_column='Paragraph', null=True)),
                ('trees', models.TextField(blank=True, db_column='Trees', null=True)),
                ('shrubs', models.TextField(blank=True, db_column='Shrubs', null=True)),
                ('succulents', models.TextField(blank=True, db_column='Succulents', null=True)),
                ('vines', models.TextField(blank=True, db_column='Vines', null=True)),
                ('vine', models.TextField(blank=True, db_column='Vine', null=True)),
                ('conifers', models.TextField(blank=True, db_column='Conifers', null=True)),
                ('grasses', models.TextField(blank=True, db_column='Grasses', null=True)),
                ('wildflowers', models.TextField(blank=True, db_column='Wildflowers', null=True)),
            ],
            options={
                'db_table': 'plant_ecoregions',
                'managed': False,
            },
        ),
    ]
